### ISSUE TITLE
Rename  hoc/Aux.js

### ISSUE THREAD

**Issue by kachaj7** [devandres-tech/Netflix-Clone#21]
Under windows the name aux for file is forbidden.

https://stackoverflow.com/questions/36225708/cannot-create-a-directory-named-aux-or-starting-by-aux-on-windows-8-1

**Comment by PurushothamanSrikanth** [comment]
`aux` is a reserved filename indeed, just as other filenames like `con`, `comX`, `lptX` & `prn`. I can rename `src/utilrepl/aux.js` to another name, but I'm not sure it will solve the issue.

**Comment by Rensykes** [comment]
@PurushothamanSrikanth Yes, it does. In a previous project I did, following a tutorial I named a file aux.js (I did it on a Mac) and when I tried to clone the repo Windows gave me errors about the file. I solved the issue by renaming the file. In my case I just renamed it to auxiliary.js

**Comment by devandres-tech** [comment]
Interesting...did not know this, good find! Anyhow, the Aux.js component **does not** exist anymore in the source code. Thanks.
