### ISSUE TITLE
Issue with npm run dev

### ISSUE THREAD

**Issue by AbenezerBayeh** [devandres-tech/Netflix-Clone#23]
Being a beginner in web pack, I'm confused with this error. Please let me know if this is an issue with the required version or something else. Thanks!

webpack-basics@1.0.0 dev /Users/abenezerayana/Downloads/Netflix-Clone-master-2
> webpack-dev-server --mode development --config webpack.config.js --open

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'webpack/bin/config-yargs'

**Comment by devandres-tech** [comment]
You can try to run the app with latest updates, which includes the latest Webpack (5) features
