### ISSUE TITLE
TypeError: Cannot convert undefined or null to object when running npm run dev on MAC

### ISSUE THREAD

**Issue by auscott** [devandres-tech/Netflix-Clone#40]
<img width="573" alt="Screenshot 2022-01-17 at 10 03 20 PM" src="https://user-images.githubusercontent.com/35914464/149782764-6b457b31-ac3c-4b24-b125-fded59c00e5b.png">

may I ask if anyone could help me solve the error when I tried to type 'npm run dev'?
Can the code be run on web environment? thanks!

**Comment by devandres-tech** [comment]
This should have been fixed with the latest Webpack (5) updates, the dev script has been updated also.
